feat: add builder io
codefensory/capsil-ecommerce pull request #1
Opened 2023-09-27 05:26 UTC by codefensory

2023-09-27 22:28 UTC, leobar37 requested changes

2023-09-27 22:28 UTC, leobar37 commented on src/components/builder.tsx
> +builder.init("332318a4394a440e8302ceeaa373f90c");
Socio, declara la variable y no la usa xd, ve que no se suba el .env este

2023-09-27 22:28 UTC, leobar37 commented on src/components/Counter/styles.module.css
> +.counter {
socio ya tenemos tailwind, hagamos todo con eso

2023-09-27 22:28 UTC, leobar37 commented
Socio, que pase esta pr primero
y depués  mergeamos la mia

2023-09-27 22:48 UTC, codefensory commented on src/components/Counter/styles.module.css
> +.counter {
Socio yo no fui xd, fue builderio, algo con su pagina demo me parece

2023-09-28 04:03 UTC, codefensory commented on src/components/builder.tsx
> +builder.init("332318a4394a440e8302ceeaa373f90c");
Ah socio pero es necesario, porque el que esta en [...page]/page se ejecuta en el server y este de aqui se ejecuta en el cliente, sin este el cliente no inicia el builderio y no funciona :cry:

2023-09-28 04:03 UTC, codefensory commented on src/components/builder.tsx
> +builder.init("332318a4394a440e8302ceeaa373f90c");
Pero si, voy a eliminar el .env y usar las variables de entorno en ves de hardcodearlo

2023-09-28 06:13 UTC, merged